# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YRQwF06TL-Rv3O_hSLiYu9skpOuCIVj5
"""

from dash import Dash, html, dcc, callback, Output, Input
import dash_ag_grid as dag
import pandas as pd
import plotly.express as px

"""#Dataset"""

df = pd.read_csv(
  "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
)

"""#App"""

external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']
app = Dash(external_stylesheets=external_stylesheets)

"""#Layout"""

app.layout = [
  html.Div(
    children="🌸 Dashboard Interactivo Iris",
    style={
      "textAlign": "center",
      "fontSize": 36,
      "fontWeight": "bold",
      "color": "#6a0dad",
      "marginBottom": "15px"
    }
  ),

"""#Filtro"""

html.Div(
    children=[
      html.Label("Filtrar por especie:", style={"fontWeight": "bold"}),
      dcc.Dropdown(
        id="filtro-especie",
        options=[{"label": i, "value": i} for i in df["species"].unique()],
        value=None,
        placeholder="Selecciona una especie (opcional)"
      )
    ],
    style={"width": "40%", "margin": "0 auto"}
  ),
  html.Br(),

"""#Radio Buttons"""

html.Div(

    children=[
      dcc.RadioItems(
        options=[
          "sepal_length",
          "sepal_width",
          "petal_length",
          "petal_width"
        ],
        value="sepal_length",
        inline=True,
        id="radio-variable"
      )
    ],
    style={"textAlign": "center", "marginBottom": "15px"}
  ),

# =========================

  # KPIs (TARJETAS)

  # =========================

  html.Div(id="kpi-container", className="row"),



  # =========================

  # CONTENIDO PRINCIPAL

  # =========================

  html.Div(

    className="row",

    children=[



      # TABLA

      html.Div(

        className="six columns",

        children=[



          dag.AgGrid(

            rowData=df.to_dict("records"),

            columnDefs=[{"field": i} for i in df.columns],

            defaultColDef={

              "sortable": True,

              "filter": True,

              "resizable": True

            },

            style={"height": "500px"}

          )

        ]

      ),



      # GRÁFICOS

      html.Div(

        className="six columns",

        children=[



          dcc.Graph(id="grafico-hist"),

          dcc.Graph(id="grafico-box"),

          dcc.Graph(id="grafico-pie")



        ]

      )

    ]

  )

]



# =========================

# ESTILO KPI CARD

# =========================

kpi_style = {

  "backgroundColor": "#ffffff",

  "padding": "20px",

  "borderRadius": "12px",

  "boxShadow": "2px 2px 12px rgba(0,0,0,0.1)",

  "textAlign": "center",

  "margin": "10px"

}



# =========================

# CALLBACK

# =========================

@callback(

  Output("grafico-hist", "figure"),

  Output("grafico-box", "figure"),

  Output("grafico-pie", "figure"),

  Output("kpi-container", "children"),

  Input("radio-variable", "value"),

  Input("filtro-especie", "value")

)

def actualizar_dashboard(variable, especie):



  dff = df.copy()



  if especie:

    dff = dff[dff["species"] == especie]



  # ================= HISTOGRAMA =================

  hist = px.histogram(

    dff,

    x="species",

    y=variable,

    color="species",

    histfunc="avg",

    title=f"Promedio de {variable} por especie"

  )

  hist.update_layout(template="plotly_white")



  # ================= BOXPLOT =================

  box = px.box(

    dff,

    x="species",

    y=variable,

    color="species",

    title=f"Distribución de {variable}"

  )

  box.update_layout(template="plotly_white")



  # ================= PIE =================

  pie = px.pie(

    dff,

    names="species",

    title="Distribución de especies"

  )

  pie.update_traces(textinfo="percent+label")



  # ================= KPIs =================

  kpi1 = html.Div([

    html.H4("📊 Total registros"),

    html.H2(len(dff))

  ], style=kpi_style)



  kpi2 = html.Div([

    html.H4("📈 Promedio"),

    html.H2(round(dff[variable].mean(), 2))

  ], style=kpi_style)



  kpi3 = html.Div([

    html.H4("📌 Máximo"),

    html.H2(round(dff[variable].max(), 2))

  ], style=kpi_style)



  kpi4 = html.Div([

    html.H4("📉 Mínimo"),

    html.H2(round(dff[variable].min(), 2))

  ], style=kpi_style)



  kpi_row = html.Div(

    className="row",

    children=[

      html.Div(kpi1, className="three columns"),

      html.Div(kpi2, className="three columns"),

      html.Div(kpi3, className="three columns"),

      html.Div(kpi4, className="three columns"),

    ],

    style={"marginBottom": "20px"}

  )



  return hist, box, pie, kpi_row





# =========================

# RUN APP

# =========================

if __name__ == "__main__":

  app.run(debug=True, port=8005, jupyter_mode="external")